<?php

declare(strict_types=1);

// Generated by bin/sync-spec.php from the OpenAPI webhooks section. Do not edit by hand.

namespace BankApi\Webhook;

/**
 * Every webhook event type of the pinned GO-KIT contract. A type missing
 * here can still arrive (a newer server): treat it as unknown, not an error.
 */
final class EventType
{
    public const BANK_CREDIT = 'bank.credit';
    public const BANK_DEBIT = 'bank.debit';
    public const BANK_PAYMENT_MATCHED = 'bank.payment.matched';
    public const FLOW_OUTPUT = 'flow.output';
    public const ORG_CREATED = 'org.created';
    public const ORG_MEMBER_INVITED = 'org.member_invited';
    public const ORG_QUOTA_EXCEEDED = 'org.quota_exceeded';
    public const SUBSCRIPTION_ACTIVATED = 'subscription.activated';
    public const SUBSCRIPTION_CANCELLED = 'subscription.cancelled';
    public const SUBSCRIPTION_EXPIRED = 'subscription.expired';
    public const SUBSCRIPTION_PAST_DUE = 'subscription.past_due';
    public const SUBSCRIPTION_RENEWED = 'subscription.renewed';

    /** @var list<string> */
    public const ALL = [
        self::BANK_CREDIT,
        self::BANK_DEBIT,
        self::BANK_PAYMENT_MATCHED,
        self::FLOW_OUTPUT,
        self::ORG_CREATED,
        self::ORG_MEMBER_INVITED,
        self::ORG_QUOTA_EXCEEDED,
        self::SUBSCRIPTION_ACTIVATED,
        self::SUBSCRIPTION_CANCELLED,
        self::SUBSCRIPTION_EXPIRED,
        self::SUBSCRIPTION_PAST_DUE,
        self::SUBSCRIPTION_RENEWED,
    ];
}
