<?php

declare(strict_types=1);

namespace BankApi;

// Generated by bin/gen-error-codes.php from packages/core/tests/fixtures/openapi.json.
// Do not edit by hand — run `composer gen:error-codes` to refresh.
final class ErrorCode
{
    public const ADMIN_USER_IS_SUPER_ADMIN = 'admin.user_is_super_admin';
    public const ADMIN_USER_SELF_SUSPEND = 'admin.user_self_suspend';
    public const AUTH_EMAIL_NOT_VERIFIED = 'auth.email_not_verified';
    public const AUTH_FLOWS_DISABLED = 'auth.flows_disabled';
    public const AUTH_INVALID_CREDENTIALS = 'auth.invalid_credentials';
    public const AUTH_REFRESH_IN_FLIGHT = 'auth.refresh_in_flight';
    public const AUTH_REFRESH_INVALID = 'auth.refresh_invalid';
    public const AUTH_REFRESH_REUSE_DETECTED = 'auth.refresh_reuse_detected';
    public const AUTH_RESET_TOKEN_INVALID = 'auth.reset_token_invalid';
    public const AUTH_RESET_UNAVAILABLE = 'auth.reset_unavailable';
    public const AUTH_SECURITY_STATE_CHANGED = 'auth.security_state_changed';
    public const AUTH_SESSION_REVOCATION_UNAVAILABLE = 'auth.session_revocation_unavailable';
    public const AUTH_TWOFA_CHALLENGE_INVALID = 'auth.twofa_challenge_invalid';
    public const AUTH_TWOFA_CODE_INVALID = 'auth.twofa_code_invalid';
    public const AUTH_TWOFA_UNAVAILABLE = 'auth.twofa_unavailable';
    public const AUTH_VERIFICATION_TOKEN_INVALID = 'auth.verification_token_invalid';
    public const AUTH_VERIFICATION_UNAVAILABLE = 'auth.verification_unavailable';
    public const BANKING_ACCOUNT_ALREADY_LINKED = 'banking.account_already_linked';
    public const BANKING_BANK_UNSUPPORTED = 'banking.bank_unsupported';
    public const BANKING_INTENT_CODE_DUPLICATE = 'banking.intent_code_duplicate';
    public const BANKING_MATCH_CONFLICT = 'banking.match_conflict';
    public const BANKING_MATCH_INVALID = 'banking.match_invalid';
    public const BANKING_OAUTH_STATE_INVALID = 'banking.oauth_state_invalid';
    public const BANKING_OTP_EXPIRED = 'banking.otp_expired';
    public const BANKING_OTP_INVALID = 'banking.otp_invalid';
    public const BANKING_OTP_LOCKED = 'banking.otp_locked';
    public const BANKING_OTP_PROVIDER_UNAVAILABLE = 'banking.otp_provider_unavailable';
    public const BANKING_OTP_STATE_CONFLICT = 'banking.otp_state_conflict';
    public const BANKING_RECIPIENT_LOOKUP_FAILED = 'banking.recipient_lookup_failed';
    public const CREDIT_CHECKOUT_CONFLICT = 'credit.checkout_conflict';
    public const CREDIT_IDEMPOTENCY_CONFLICT = 'credit.idempotency_conflict';
    public const CREDIT_INSUFFICIENT_CREDIT = 'credit.insufficient_credit';
    public const FLOW_CONDITION_INVALID = 'flow.condition_invalid';
    public const FLOW_CONDITIONS_UNSUPPORTED = 'flow.conditions_unsupported';
    public const FLOW_CONNECTOR_INVALID = 'flow.connector_invalid';
    public const FLOW_GRAPH_INVALID = 'flow.graph_invalid';
    public const FLOW_QUOTA_EXCEEDED = 'flow.quota_exceeded';
    public const FLOW_TRIGGER_INVALID = 'flow.trigger_invalid';
    public const IDEMPOTENCY_IN_PROGRESS = 'idempotency.in_progress';
    public const IDEMPOTENCY_KEY_INVALID = 'idempotency.key_invalid';
    public const IDEMPOTENCY_KEY_REUSED = 'idempotency.key_reused';
    public const ORG_HAS_ACTIVE_BANK_CONSENT = 'org.has_active_bank_consent';
    public const ORG_HAS_BANK_TRANSACTIONS = 'org.has_bank_transactions';
    public const ORG_MEMBER_LAST_OWNER = 'org.member_last_owner';
    public const PAYMENT_GATEWAY_UNAVAILABLE = 'payment.gateway_unavailable';
    public const PAYMENT_STATE_INVALID = 'payment.state_invalid';
    public const STOREFRONT_BUY_THROTTLED = 'storefront.buy_throttled';
    public const STOREFRONT_IDEMPOTENCY_CONFLICT = 'storefront.idempotency_conflict';
    public const STOREFRONT_INSUFFICIENT_CREDIT = 'storefront.insufficient_credit';
    public const STOREFRONT_OUT_OF_STOCK = 'storefront.out_of_stock';
    public const STOREFRONT_PAYLOAD_GONE = 'storefront.payload_gone';
    public const STOREFRONT_PRICE_TOO_LARGE = 'storefront.price_too_large';
    public const STOREFRONT_PURCHASE_REJECTED = 'storefront.purchase_rejected';
    public const STOREFRONT_SELF_PURCHASE = 'storefront.self_purchase';
    public const STOREFRONT_UNAVAILABLE = 'storefront.unavailable';

    /** @var list<string> */
    public const ALL = [
        'admin.user_is_super_admin',
        'admin.user_self_suspend',
        'auth.email_not_verified',
        'auth.flows_disabled',
        'auth.invalid_credentials',
        'auth.refresh_in_flight',
        'auth.refresh_invalid',
        'auth.refresh_reuse_detected',
        'auth.reset_token_invalid',
        'auth.reset_unavailable',
        'auth.security_state_changed',
        'auth.session_revocation_unavailable',
        'auth.twofa_challenge_invalid',
        'auth.twofa_code_invalid',
        'auth.twofa_unavailable',
        'auth.verification_token_invalid',
        'auth.verification_unavailable',
        'banking.account_already_linked',
        'banking.bank_unsupported',
        'banking.intent_code_duplicate',
        'banking.match_conflict',
        'banking.match_invalid',
        'banking.oauth_state_invalid',
        'banking.otp_expired',
        'banking.otp_invalid',
        'banking.otp_locked',
        'banking.otp_provider_unavailable',
        'banking.otp_state_conflict',
        'banking.recipient_lookup_failed',
        'credit.checkout_conflict',
        'credit.idempotency_conflict',
        'credit.insufficient_credit',
        'flow.condition_invalid',
        'flow.conditions_unsupported',
        'flow.connector_invalid',
        'flow.graph_invalid',
        'flow.quota_exceeded',
        'flow.trigger_invalid',
        'idempotency.in_progress',
        'idempotency.key_invalid',
        'idempotency.key_reused',
        'org.has_active_bank_consent',
        'org.has_bank_transactions',
        'org.member_last_owner',
        'payment.gateway_unavailable',
        'payment.state_invalid',
        'storefront.buy_throttled',
        'storefront.idempotency_conflict',
        'storefront.insufficient_credit',
        'storefront.out_of_stock',
        'storefront.payload_gone',
        'storefront.price_too_large',
        'storefront.purchase_rejected',
        'storefront.self_purchase',
        'storefront.unavailable',
    ];

    public static function isKnown(?string $code): bool
    {
        return $code !== null && in_array($code, self::ALL, true);
    }
}
